name: p2p_qr_call
description: P2P call demo via QR
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  flutter_sound: 9.28.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  image_picker: ^1.0.7
  hive: ^2.2.3

  flutter_webrtc: ^1.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  uuid: ^4.5.2

flutter:
  uses-material-design: true
